import React from "react";
import MetricChannel from "./MetricChannel";

const MetricsMixer = ({ currMetrics, setMetrics }) => {

  return (
      <div id="mixer">
        <MetricChannel
          metric="acousticness"
          min={0}
          max={1}
          defaultValue={currMetrics.acousticness}
          step={0.01}
          maxEmoji="🏞️"
          minEmoji="🏙️"
          currMetrics={currMetrics}
          setMetrics={setMetrics}
        />
        <MetricChannel 
          metric="danceability"
          min={0}
          max={1}
          defaultValue={currMetrics.danceability}
          step={0.01}
          maxEmoji="🥳"
          minEmoji="😐"
          currMetrics={currMetrics}
          setMetrics={setMetrics}
        />
        <MetricChannel 
          metric="energy"
          min={0}
          max={1}
          defaultValue={currMetrics.energy}
          step={0.01}
          maxEmoji="🔋"
          minEmoji="🪫"
          currMetrics={currMetrics}
          setMetrics={setMetrics}
        />
        <MetricChannel 
          metric="instrumentalness"
          min={0}
          max={1}
          defaultValue={currMetrics.instrumentalness}
          step={0.01}
          maxEmoji="🎺"
          minEmoji="🎙️"
          currMetrics={currMetrics}
          setMetrics={setMetrics}
        />
        <MetricChannel 
          metric="liveness"
          min={0}
          max={1}
          defaultValue={currMetrics.liveness}
          step={0.01}
          maxEmoji="🎫"
          minEmoji="🎧"
          currMetrics={currMetrics}
          setMetrics={setMetrics}
        />
        <MetricChannel 
          metric="speechiness"
          min={0}
          max={1}
          defaultValue={currMetrics.speechiness}
          step={0.01}
          maxEmoji="🗣️"
          minEmoji="🎶"
          currMetrics={currMetrics}
          setMetrics={setMetrics}
        />
        <MetricChannel 
          metric="valence"
          min={0}
          max={1}
          defaultValue={currMetrics.valence}
          step={0.01}
          maxEmoji="🥹"
          minEmoji="🥺"
          currMetrics={currMetrics}
          setMetrics={setMetrics}
        />
        <MetricChannel 
          metric="loudness"
          min={-60}
          max={0}
          defaultValue={currMetrics.loudness}
          step={1}
          maxEmoji="💥"
          minEmoji="🦗"
          currMetrics={currMetrics}
          setMetrics={setMetrics}
        />
        <MetricChannel 
          metric="tempo"
          min={0}
          max={240}
          defaultValue={currMetrics.tempo}
          step={1}
          maxEmoji="🚀"
          minEmoji="🐌"
          currMetrics={currMetrics}
          setMetrics={setMetrics}
        />
      </div>
    );
  }

  export default MetricsMixer;